version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - node_modules

      - run: npm run test:ci
      - run: npm run build
      - run: npm run netlify:deploy
